export default {
  // User
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
  EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILS: 'SIGNIN_FAILS',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGNOUT_START: 'SIGNOUT_START',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILS: 'SIGNOUT_FAILS',
  // Cart
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  // Shop
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILS: 'FETCH_COLLECTIONS_FAILS',
};
