export default {
  // User
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  // Cart
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  // Shop
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
};
